import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-900 text-gray-200 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-800 text-white p-4">
          <h1 className="text-2xl font-bold">P2P Emergency Fund</h1>
        </header>
        <main>{children}</main>
        <footer className="bg-gray-800 text-gray-400 text-center p-4 mt-auto">
          <p>© 2025 P2P Emergency Fund</p>
        </footer>
      </body>
    </html>
  );
}
